version: '2'
services:
  web:
    build: .
    command: node .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8432:8432"
    environment:
      OMDB_API_KEY: b35bef8